# Generated by Django 3.2.8 on 2023-07-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_appointment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
