# Generated by Django 4.2.3 on 2023-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Faculty', 'Faculty'), ('Admin', 'Admin'), ('FeedbackOfficer', 'FeedbackOfficer')], default='Select your role', max_length=50, null=True),
        ),
    ]
