# Generated by Django 4.2.3 on 2023-08-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_emotion_lecture_delete_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotions', models.JSONField(default=dict)),
                ('percentages', models.JSONField(default=dict)),
            ],
        ),
    ]
