# Generated by Django 4.2.3 on 2023-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_lecture_lecture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'Faculty'), ('Feedbackofficer', 'Feedbackofficer')], default='Select your role', max_length=50, null=True),
        ),
    ]
